name: Publish

on:
  push:
    branches:
      - main
      - beta
  workflow_dispatch:

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ™Œ Prepare release
        id: release-please
        uses: google-github-actions/release-please-action@v3
        with:
          release-type: simple
          token: ${{ secrets.ACCESS_TOKEN }}
          extra-files: database.dbml
          pull-request-title-pattern: "chore${scope}: release${component} v${version}"
          package-name: "open-discogs-erd"
    outputs:
      release_created: ${{ steps.release-please.outputs.release_created }}
      tag_name: ${{ steps.release-please.outputs.tag_name }}
  publish:
    name: Publish
    runs-on: ubuntu-latest
    needs: release
    steps:
      - name: ğŸ Setup Python
        uses: actions/setup-python@v4
      - name: â˜• Setup Node
        uses: actions/setup-node@v3
      - name: ğŸ§ª Install dbdocs
        run: npm install -g dbdocs
      - name: ğŸ” Check dbdocs
        run: dbdocs
      - name: âœ¨ Checkout repository
        uses: actions/checkout@v3
      - name: ğŸ± Write prepend files
        run: |
          python prepend.py database.dbml 'Open Discogs Beta'
	        python prepend.py database.dbml 'Open Discogs'
      - name: ğŸ“¦ Update dbdocs main project
        if: ${{ github.ref == 'refs/heads/main' }}
        env:
          DBDOCS_TOKEN: ${{ secrets.DBDOCS_TOKEN }}
        run: dbdocs build ./open_discogs_prepended.dbml
      - name: ğŸ“¦ Update dbdocs beta project
        if: ${{ github.ref == 'refs/heads/beta' }}
        env:
          DBDOCS_TOKEN: ${{ secrets.DBDOCS_TOKEN }}
        run: dbdocs build ./open_discogs_beta_prepended.dbml
