name: Publish Beta

on:
  push:
    branches:
      - beta
  workflow_run:
    workflows: ["Release"]
  types:
    - completed
  workflow_dispatch:
  
jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    needs: release
    steps:
      - name: ğŸ Setup Python
        uses: actions/setup-python@v4
      - name: â˜• Setup Node
        uses: actions/setup-node@v3
      - name: ğŸ§ª Install dbdocs
        run: npm install -g dbdocs
      - name: ğŸ” Check dbdocs
        run: dbdocs
      - name: âœ¨ Checkout repository
        uses: actions/checkout@v3
      - name: ğŸ± Write prepended dbml
        run: python prepend.py database.dbml 'Open Discogs Beta'
      - name: ğŸ“¦ Update dbdocs
        env:
          DBDOCS_TOKEN: ${{ secrets.DBDOCS_TOKEN }}
        run: dbdocs build ./open_discogs_beta_prepended.dbml